<template>
  <div class="col-sm-12 col-xs-12 col-md-6 col-lg-6">
    <q-card class="cartao_grade cartao_grade_ok shadow-1 q-ma-sm">
      <div class="row">
        <q-card-section class="cartao_grade_titulo">
          <span>#24. Create UI design model</span>
        </q-card-section>
        <q-card-section class="cartao_grade_corpo">
          <p>One morning, when Gregor Samsa woke from troubled...</p>
          <div class="cartao_grade_corpo_detalhes">
            <span>28 January, 2015</span>
            <div class="row dropdown_prioridade">
              <span class="dropdown_prioridade_rotulo">Prioridade:</span>
              <q-select
                outlined
                class="dropdown_select"
                v-model="prioridade"
                :options="options"
                option-label="value"
                dense
                emit-value
                map-options
              />
            </div>
            <span>Eternity app</span>
          </div>
        </q-card-section>
        <q-card-section class="cartao_grade_participantes absolute-left">
          <q-avatar>
            <img src="https://cdn.quasar.dev/img/avatar.png">
          </q-avatar>
          <q-avatar>
            <img src="https://cdn.quasar.dev/img/avatar.png">
          </q-avatar>
          <q-avatar>
            <img src="https://cdn.quasar.dev/img/avatar.png">
          </q-avatar>
        </q-card-section>
        <q-card-section class="cartao_grade_complementos absolute-bottom">
          Due: 23 hours
        </q-card-section>
      </div>
    </q-card>
  </div>
</template>

<script>
  export default {
    name: "CartaoGrade",
    data() {
      return {
        prioridade: '',
        options: [
          {
            label: 'Bloqueado',
            value: 'Bloq'
          },
          {
            label: 'Alta Prioridade',
            value: 'Alta'
          },
          {
            label: 'Média Prioridade',
            value: 'Media'
          },
          {
            label: 'Baixa Prioridade',
            value: 'Baixa'
          }
        ]
      }
    }
  }
</script>

<style lang="scss">
  .cartao_grade {
    height: 202px !important;
    border: 1px solid rgba(0, 0, 0, .125);
    border-radius: 10px;
    -webkit-animation: scale-in-ver-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: scale-in-ver-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

    &_titulo {
      cursor: pointer;
      font-weight: bold;
      font-size: .9375rem;
      height: 30px;
    }

    &_titulo:hover {
      text-decoration: underline;
      color: #0089ba;
    }

    &_corpo {
      position: absolute;
      margin-top: 50px;
      width: 100%;

      .cartao_grade_corpo_detalhes {
        float: right;
        display: flex;
        flex-direction: column;
        margin-top: -80px;
      }

      .cartao_grade_corpo_detalhes span {
        margin-bottom: 5px;
      }

      .cartao_grade_corpo_detalhes span:first-child:not(.dropdown_prioridade_rotulo) {
        color: #999999;
      }
    }

    .cartao_grade_participantes {
      margin-top: 80px;
      float: left;

      .q-avatar {
        margin-right: 10px !important;
      }
    }

    .dropdown_prioridade_rotulo {
      margin-top: 5px;
      margin-right: 3px;
    }

    &_complementos {
      background: rgba(0, 0, 0, .02);
      padding: .9375rem 1.25rem;
      border-top: 1px solid rgba(0, 0, 0, .125);
    }
  }

  .cartao_grade_ok {
    border-left: 3px solid $positive;
  }

  .cartao_grade_nok {
    border-left: 3px solid $negative;
  }

  .dropdown_select .q-field__inner .q-field__control {
    min-height: 30px !important;
    height: 30px !important;
  }

  .dropdown_select .q-select__dropdown-icon {
    margin-top: -11px;
    margin-right: -10px !important;
  }

  .dropdown_select .q-field__native {
    font-size: 75%;
    margin-top: -2px !important;
  }

  @media (max-width: 800px) {
    .cartao_grade_corpo_detalhes {
      flex-direction: row;
    }
  }

  /* ----------------------------------------------
   * Generated by Animista on 2020-2-16 11:33:16
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info.
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation scale-in-ver-center
   * ----------------------------------------
   */
  @-webkit-keyframes scale-in-ver-center {
    0% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      opacity: 1;
    }
  }
  @keyframes scale-in-ver-center {
    0% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      opacity: 1;
    }
  }

</style>

