<template>
  <div class="col-sm-12 col-xs-12 col-md-6 col-lg-6">
    <q-card
      :class="'cartao_grade ' + getClassePrioridade() + ' shadow-1 q-ma-sm'"
    >
      <div class="row">
        <q-card-section class="cartao_grade_titulo">
          <span>{{ projeto.titulo }}</span>
        </q-card-section>
        <q-card-section class="cartao_grade_corpo">
          <p>One morning, when Gregor Samsa woke from troubled...</p>
          <div class="cartao_grade_corpo_detalhes">
            <span>{{ projeto.criadoEm }}</span>
            <div class="row dropdown_prioridade">
              <span class="dropdown_prioridade_rotulo">Prioridade:</span>
              <q-select
                outlined
                class="dropdown_select"
                v-model="projeto.prioridade"
                :options="options"
                option-label="value"
                dense
                emit-value
                map-options
              />
            </div>
            <span>Eternity app</span>
          </div>
        </q-card-section>
        <q-card-section class="cartao_grade_participantes absolute-left">
          <q-avatar>
            <img
              src="https://api.adorable.io/avatars/400/24aa74636ad3163ad52506db34f54b2b.png"
            />
          </q-avatar>
          <q-avatar>
            <img
              src="https://api.adorable.io/avatars/400/4469e1b0130956bc3d022dad518b1026.png"
            />
          </q-avatar>
          <q-avatar>
            <img
              src="https://api.adorable.io/avatars/400/c1277c1db86d6f27f34a7e5575746f49.png"
            />
          </q-avatar>
        </q-card-section>
        <q-card-section class="cartao_grade_complementos absolute-bottom">
          Vence Em: {{ projeto.venceEm }}
        </q-card-section>
      </div>
    </q-card>
  </div>
</template>

<script>
export default {
  name: "CartaoGrade",
  props: ["projeto"],
  data() {
    return {
      //prioridade: "",
      options: [
        {
          label: "Bloqueado",
          value: "Bloq"
        },
        {
          label: "Alta Prioridade",
          value: "Alta"
        },
        {
          label: "Média Prioridade",
          value: "Media"
        },
        {
          label: "Baixa Prioridade",
          value: "Baixa"
        }
      ]
    };
  },
  methods: {
    getClassePrioridade() {
      const classes = {
        Alta: () => "cartao_grade_alta_prioridade",
        Média: () => "cartao_grade_media_prioridade",
        Baixa: () => "cartao_grade_baixa_prioridade",
        default: () => "cartao_grade_baixa_prioridade"
      };
      return (classes[this.projeto.prioridade] || classes["default"])();
    }
  }
};
</script>

<style lang="scss">
.cartao_grade {
  height: 202px !important;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 10px;
  -webkit-animation: scale-in-ver-center 0.5s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-ver-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  &_titulo {
    cursor: pointer;
    font-weight: bold;
    font-size: 0.9375rem;
    height: 30px;
  }
  &_titulo:hover {
    text-decoration: underline;
    color: #0089ba;
  }
  &_corpo {
    position: absolute;
    margin-top: 50px;
    width: 100%;
    .cartao_grade_corpo_detalhes {
      float: right;
      display: flex;
      flex-direction: column;
      margin-top: -80px;
    }
    .cartao_grade_corpo_detalhes span {
      margin-bottom: 5px;
    }
    .cartao_grade_corpo_detalhes
      span:first-child:not(.dropdown_prioridade_rotulo) {
      color: #999999;
    }
  }
  .cartao_grade_participantes {
    margin-top: 80px;
    float: left;
    .q-avatar {
      margin-right: 10px !important;
    }
  }
  .dropdown_prioridade_rotulo {
    margin-top: 5px;
    margin-right: 3px;
  }
  &_complementos {
    background: rgba(0, 0, 0, 0.02);
    padding: 0.9375rem 1.25rem;
    border-top: 1px solid rgba(0, 0, 0, 0.125);
  }
}
.cartao_grade_media_prioridade {
  border-left: 3px solid $warning;
}
.cartao_grade_baixa_prioridade {
  border-left: 3px solid $positive;
}
.cartao_grade_alta_prioridade {
  border-left: 3px solid $negative;
}
.dropdown_select .q-field__inner .q-field__control {
  min-height: 30px !important;
  height: 30px !important;
}
.dropdown_select .q-select__dropdown-icon {
  margin-top: -11px;
  margin-right: -10px !important;
}
.dropdown_select .q-field__native {
  font-size: 75%;
  margin-top: -2px !important;
}
@media (max-width: 800px) {
  .cartao_grade_corpo_detalhes {
    flex-direction: row;
  }
}
/* ----------------------------------------------
   * Generated by Animista on 2020-2-16 11:33:16
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info.
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */
/**
   * ----------------------------------------
   * animation scale-in-ver-center
   * ----------------------------------------
   */
@-webkit-keyframes scale-in-ver-center {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    opacity: 1;
  }
}
@keyframes scale-in-ver-center {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    opacity: 1;
  }
}
</style>
